### ISSUE TITLE
newpage option forces first problem onto second page

### ISSUE THREAD

**Issue by RockemRobotics** [artemmavrin/latex-homework#2]
As the title says, using the newpage option forces the first problem onto the second page, rather than leaving it on the first page.

**Comment by artemmavrin** [comment]
Are you manually numbering your problems? I might have fixed the issue just now: 670f0915ed536747d8cfa2bb69d0ec3a02c8b490.

**Comment by RockemRobotics** [comment]
I just tried it with the new version of homework.cls, and it worked perfectly!  Yes, I was re-numbering my problems, if that helps with troubleshooting.  My first exercise of the homework set was problem 12.

**Comment by artemmavrin** [comment]
Great, I'm glad it works now. Thanks for catching that bug!
