### ISSUE TITLE
Including solution after part leading to large blank spaces

### ISSUE THREAD

**Issue by lpdx** [artemmavrin/latex-homework#4]
It's a really nice class but I'm having an issue that I can't solve by myself.

When I try to put the solution right after the part of the problem I'm getting a large white space.
I'm using Overleaf to compile.

Here is the screen capture.

![image](https://user-images.githubusercontent.com/13546280/53198043-39d70600-35fa-11e9-8ce2-a3e5effc528d.png)

And the minimal example:
>\documentclass{homework}
>\name{Leonhard Euler}
>\course{Math 101}
>\term{Fall 1737}
>\hwnum{1}
> \begin{problem}
>Problem description
> \begin{parts}
>\part
>\label{1.a}
>$log_22 = x$
>\begin{solution}
> solution
>\end{solution}
>\part
>\label{1.b}
> Problem b
>\begin{solution}
> solution
>\end{solution}
>\end{problem}
>\end{document}

**Comment by artemmavrin** [comment]
Your minimal example is missing a `\begin{document}` and an `\end{parts}`, but that isn't the problem. 

Your usage (putting solutions in between problem parts) isn't the *intended* way to use the class, but I think it may still work how you want if you make the following changes:

```tex
\documentclass{homework}
\name{Leonhard Euler}
\course{Math 101}
\term{Fall 1737}
\hwnum{1}
\begin{document}
\begin{problem}
Problem description
\begin{parts}
\part
\label{1.a}
$log_22 = x$
\end{parts} % End the parts environment before the solution environment
\begin{solution}
solution
\end{solution}
\begin{parts} % Start a new parts environment after the solution
\part
\label{1.b}
Problem b
\end{parts} % End of the parts environment before the solution environment
\begin{solution}
solution
\end{solution}
\end{problem}
\end{document}
```
This works for me on Overleaf, producing the following:
![capture](https://user-images.githubusercontent.com/12015989/53198948-9d4d3d80-35d2-11e9-93fa-76f82b3b77ff.PNG)

Hope this helps!

**Comment by lpdx** [comment]
Works really well!
Thank you a lot!
